"""empty message

Revision ID: b263903cc7f0
Revises: 6098e9ec6637
Create Date: 2021-04-04 05:47:16.833794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b263903cc7f0'
down_revision = '6098e9ec6637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_link')
    # ### end Alembic commands ###
